version: "3.6"

services:
  peripheral-manager-gpu:
    build: .
    restart: on-failure
    volumes:
      - /etc/:/etcfs/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/lib/:/usr/lib/:ro
      - /dev/:/dev/:ro
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production