version: "3.7"

services:
  peripheral-manager-gpu:
    build: .
    restart: on-failure
    volumes:
      - /etc/:/etc/:ro
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production